services:
  weather_api:
    build:
      no_cache: true
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - weather_api_postgres_db
    restart: always

  weather_api_postgres_db:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_api

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.3
    env_file:
      - .env
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=weather_api_postgres_db port=5432 user=postgres password=postgres dbname=weather_api
    depends_on:
      - weather_api_postgres_db
    restart: on-failure:10
    volumes:
      - ./db/migration:/migrations